parameters:
#    stas_recycle.example.class: Stas\RecycleBundle\Example

services:
#    stas_recycle.example:
#        class: %stas_recycle.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
